### ISSUE TITLE
Installation via conda?

### ISSUE THREAD

**Issue by joshua-laughner** [TCCON/ggg-rs#4]
Since `conda` has a `rust` package available it is possible to build Rust binaries in a conda recipe and install that conda package. Here's a proof-of-concept `meta.yaml` file for `jrep`:

```yaml
package:
  name: "jrep"
  version: "0.1.3"

source:
  git_rev: "v0.1.3"
  git_url: "https://github.com/joshua-laughner/jrep"

build:
  # Because there are custom C/C++ compilers and linkers that Anaconda
  # provides that aren't named what rustc expects, we have to tell it to use the
  # one they define in their $CC variable. We also have to install to $PREFIX,
  # because that is where the builder can copy files from
  script: RUSTFLAGS="-C linker=$CC" cargo install --path . --root $PREFIX

requirements:
  # We need the C compiler to provide a linker (which we use above).
  # Then a rust toolchain, obviously.
  # I saw `{{ stdlib('c') }}` used in the libnetcdf meta.yaml file
  # (https://github.com/conda-forge/libnetcdf-feedstock/blob/main/recipe/meta.yaml),
  # but I got an error when I tried to use it.
  build:
    - {{ compiler('c') }}
    - rust

# This section can be omitted, you will get .crates.toml and .crates2.json in the output
# if you omit this though. And trying to just exclude those won't work.
outputs:
  - name: jrep
    files:
      - bin/jrep
```
I built this on a Debian Docker container and was able to install it in an environment on my regular desktop and confirmed it could run. (I installed it with `conda install --offline ./TARFILE`.) This also worked on ccycle, which proves it can cross the Debian to RHEL divide. I'll try it on a Mac later.

Now, `ggg-rs` will be more difficult - it will definitely need `libnetcdf` as a [run dependency](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#run) for example. And, in the past, I know Nick has hit GLIBC incompatibilities with pre-compiled netCDF Rust tools (this was the Phase 2 checker). Hopefully, by relying on the `libnetcdf` Conda package, this won't be an issue.
